using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CombatManager : MonoBehaviour
{
    private static object _lockingObject = new object();
    private static CombatManager _instance = null;

    public static CombatManager Instance { get { return _instance; } }

    [Header("COMBAT ROWS")]
    public CombatRow PlayerCombatRow;
    public CombatRow EnemyCombatRow;

    [Header("TEST BATTLE")]
    public int MaxSlots = 5;
    public List<CombatHandler> PlayerTeam = new List<CombatHandler>();
    public List<CombatHandler> EnemyTeam = new List<CombatHandler>();


    public void Awake()
    {
        if (!_instance)
        {
            lock (_lockingObject)
            {
                if (!_instance)
                {
                    _instance = this;
                }
            }
        }
        else
        {
            Destroy(this.gameObject);
        }
    }

    private void Start()
    {
        StartCombat();
    }

    public void StartCombat()
    {
        //Place participants into corresponding rows.
        PlayerCombatRow.Initialize(5, PlayerTeam);
        EnemyCombatRow.Initialize(5, EnemyTeam);

        //Have participants, turn by turn, attack each other simultaneously until one side has no more participants.
        //Each 'turn' of combat is deconstructed in Phases, where both Player and Enemy team actions are listed.
        //Phases are lists of actions, and Enemy and Player phase actions are done simultaneously. (All actions of a Phase take the same amount of time to 'enact')
        //Once all actions of both teams are done, there is a new phase check, to see if additional actions were generated by the actions of the previous phase.
        //If there is a new phase, all actions of that phase are done.
        //Sometimes, a team can 'skip' a phase, depending on the actions done by the other team. This is not an issue, as even if a team's phase has no actions, they are still technically participating in a phase.
        //This continues until there are no more actions in either phase, at which point a clash happens.
        //During a clash, both frontline participants hit each other for their attack values.
        //Following a clash, there is another phase check.
        //Once no more actions are in either phase, participants who have 0 Health or lower die, leaving their slot open.
        //If there are open slots that are found in front of characters, they move into that slot.

        //EVENTS can call phase checks. The end of a phase check is an event.
        //Clashes, a character dying, a character being hit, a character being healed - all of these can cause phase check requests.
        //If a phase check request is detected, the actions of the following phase are checked - if there are any, generate a phase for both teams.
    }
}
