using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CombatManager : MonoBehaviour
{
    private static object _lockingObject = new object();
    private static CombatManager _instance = null;

    public static CombatManager Instance { get { return _instance; } }

    [Header("COMBAT ROWS")]
    public CombatRow PlayerCombatRow;
    public CombatRow EnemyCombatRow;

    [Header("UNIVERSAL ACTIONS")]
    public Action_Attack AttackAction;
    public Action_ClearCorpse ClearCorpseAction;

    [Header("TEST BATTLE")]
    public int MaxSlots = 5;
    public List<CombatHandler> PlayerTeam = new List<CombatHandler>();
    public List<CombatHandler> EnemyTeam = new List<CombatHandler>();

    private Coroutine _phaseSequenceCo = null;
    public bool UnderGoingPhaseSequence { get { return _phaseSequenceCo != null; } }
    private float _phaseDuration = 1f;
    private float _currentPhaseTimer = 0f;

    private CombatPhase _currentPhase = null;
    private CombatPhase _nextPhase = null;

    public void Initialize()
    {
        GameManager.Instance.CombatManager = this;
        _instance = this;
    }

    public void StartCombat()
    {
        //Listen for action call events.
        if (EventDispatcher.Instance != null)
        {
            EventDispatcher.Instance.ActionCalled -= OnActionCalled;
            EventDispatcher.Instance.ActionCalled += OnActionCalled;
        }

        //Place participants into corresponding rows.
        PlayerCombatRow.Initialize(5, PlayerTeam);
        EnemyCombatRow.Initialize(5, EnemyTeam);

        StartCombatSequence();

        //Have participants, turn by turn, attack each other simultaneously until one side has no more participants.
        //Each 'turn' of combat is deconstructed in Phases, where both Player and Enemy team actions are listed.
        //Phases are lists of actions, and Enemy and Player phase actions are done simultaneously. (All actions of a Phase take the same amount of time to 'enact')
        //Once all actions of both teams are done, there is a new phase check, to see if additional actions were generated by the actions of the previous phase.
        //If there is a new phase, all actions of that phase are done.
        //Sometimes, a team can 'skip' a phase, depending on the actions done by the other team. This is not an issue, as even if a team's phase has no actions, they are still technically participating in a phase.
        //This continues until there are no more actions in either phase, at which point a clash happens.
        //During a clash, both frontline participants hit each other for their attack values.
        //Following a clash, there is another phase check.
        //Once no more actions are in either phase, participants who have 0 Health or lower die, leaving their slot open.
        //If there are open slots that are found in front of characters, they move into that slot.

        //EVENTS can call phase checks. The end of a phase check is an event.
        //Clashes, a character dying, a character being hit, a character being healed - all of these can cause phase check requests.
        //If a phase check request is detected, the actions of the following phase are checked - if there are any, generate a phase for both teams.
    }

    private void StartCombatSequence()
    {
        if (PhaseCheck())
        {
            _phaseSequenceCo = StartCoroutine(PhaseSequenceCo());
        }
        else
        {
            //If everyone is dead, end combat.
            bool playersDead = PlayerCombatRow.AreAllCombatantsDead();
            bool enemiesDead = EnemyCombatRow.AreAllCombatantsDead();
            if (playersDead || enemiesDead)
            {
                EndCombat();
                if (playersDead)
                {
                    Debug.LogWarning("The players were defeated!");
                }
                if (enemiesDead)
                {
                    Debug.LogWarning("The enemies were defeated!");
                }
                return;
            }

            //If some combatants are dead, clear their corpses and move everyone alive up.
            List<CombatHandler> deadPlayercombatants = PlayerCombatRow.GetDeadCombatants();
            List<CombatHandler> deadEnemycombatants = EnemyCombatRow.GetDeadCombatants();
            if (deadPlayercombatants.Count > 0 || deadEnemycombatants.Count > 0)
            {
                _currentPhase = new CombatPhase();
                foreach (CombatHandler deadPlayer in deadPlayercombatants)
                {
                    TWAction playerClearCorpseAction = ClearCorpseAction.GenerateAction(deadPlayer.gameObject, new List<GameObject>());
                    _currentPhase.PhaseActions.Add(playerClearCorpseAction);
                }

                foreach (CombatHandler deadEnemy in deadEnemycombatants)
                {
                    TWAction enemyClearCorpseAction = ClearCorpseAction.GenerateAction(deadEnemy.gameObject, new List<GameObject>());
                    _currentPhase.PhaseActions.Add(enemyClearCorpseAction);
                }

                _phaseSequenceCo = StartCoroutine(PhaseSequenceCo());

                PlayerCombatRow.MoveAllFightersUp();
                EnemyCombatRow.MoveAllFightersUp();
            }      
            else
            {
                //Otherwise, attack and proceed as normal.

                _currentPhase = new CombatPhase();
                List<GameObject> playerTarget = new List<GameObject>();
                playerTarget.Add(EnemyCombatRow.Slots[0].gameObject);
                List<GameObject> enemyTarget = new List<GameObject>();
                enemyTarget.Add(PlayerCombatRow.Slots[0].gameObject);
                TWAction playerAttackAction = AttackAction.GenerateAction(PlayerCombatRow.Slots[0].gameObject, playerTarget);
                TWAction enemyAttackAction = AttackAction.GenerateAction(EnemyCombatRow.Slots[0].gameObject, enemyTarget);
                _currentPhase.PhaseActions.Add(playerAttackAction);
                _currentPhase.PhaseActions.Add(enemyAttackAction);

                _phaseSequenceCo = StartCoroutine(PhaseSequenceCo());
            }
        }
    }

    private bool PhaseCheck()
    {
        bool proceedToNextPhase = false;
        if (_nextPhase != null)
        {
            _currentPhase = _nextPhase;
            _nextPhase = null;
        }

        return proceedToNextPhase;
    }

    private IEnumerator PhaseSequenceCo()
    {
        _currentPhase.EnactAllPhaseActions();
        _currentPhaseTimer = _phaseDuration;

        while (_currentPhaseTimer > 0f)
        {
            _currentPhaseTimer -= Time.deltaTime;
            yield return null;
        }

        _phaseSequenceCo = null;
        StartCombatSequence();
    }

    public void EndCombat()
    {
        //Stop listening for action call events.
        if (EventDispatcher.Instance != null)
        {
            EventDispatcher.Instance.ActionCalled -= OnActionCalled;
        }

        //Remove combatants from combat.
        PlayerCombatRow.ClearRow();
        EnemyCombatRow.ClearRow();
    }

    private void OnActionCalled(TWAction action)
    {
        //If no next phase has been created yet, make one.
        if (_nextPhase == null)
        {
            _nextPhase = new CombatPhase();
        }

        //Add action to next phase's list of actions.
        _nextPhase.PhaseActions.Add(action);
    }
}
